Further increase JVM's memory limits, from 4GB to 8GB
Because we were experiencing errors:

java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: GC overhead limit exceeded